library(rvest)
library(dplyr)
link='https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting'
#path=path_allowed(link)
web=read_html(link)
team=web %>% html_nodes('.poly-object-fit , .promo__text-container--with-image , iframe , .AUS') %>% html_text()
View(team)
matches=web %>% html_nodes('.poly-object-fit , .promo__text-container--with-image , iframe , .rankings-block__banner--matches') %>% html_text()
View(matches)
points=web %>% html_nodes('.poly-object-fit , .promo__text-container--with-image , iframe , .rankings-block__banner--points') %>% html_text()
View(points)
rating=data.frame(team,matches,points)
View(rating)
write.csv(rating,'test rating.csv')